name: healthbridge_ai_assistant
description: A healthcare AI app for underserved communities.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  geolocator: ^13.0.4
  google_maps_flutter: ^2.2.3
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_generative_ai: ^0.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/.env

dev_dependencies:
  flutter_lints: ^2.0.0