// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0IiIZ3y_PNnQGqxv7Rews3tXbiZmG5f0',
    appId: '1:539042072464:web:d5e2faaf7c5c41ea2cd515',
    messagingSenderId: '539042072464',
    projectId: 'healthbridgeai-c7479',
    authDomain: 'healthbridgeai-c7479.firebaseapp.com',
    storageBucket: 'healthbridgeai-c7479.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1H-zl_D46h1j5n_W6MmBFJTCHv5-ljGA',
    appId: '1:539042072464:android:a63a8726b4c15fdf2cd515',
    messagingSenderId: '539042072464',
    projectId: 'healthbridgeai-c7479',
    storageBucket: 'healthbridgeai-c7479.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSEcgXgZ_yFEAartod2rwef_lqQWeSts',
    appId: '1:539042072464:ios:734a30610444e3332cd515',
    messagingSenderId: '539042072464',
    projectId: 'healthbridgeai-c7479',
    storageBucket: 'healthbridgeai-c7479.firebasestorage.app',
    iosBundleId: 'com.example.healthbridgeAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUSEcgXgZ_yFEAartod2rwef_lqQWeSts',
    appId: '1:539042072464:ios:734a30610444e3332cd515',
    messagingSenderId: '539042072464',
    projectId: 'healthbridgeai-c7479',
    storageBucket: 'healthbridgeai-c7479.firebasestorage.app',
    iosBundleId: 'com.example.healthbridgeAiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0IiIZ3y_PNnQGqxv7Rews3tXbiZmG5f0',
    appId: '1:539042072464:web:fec4707a6bac31b62cd515',
    messagingSenderId: '539042072464',
    projectId: 'healthbridgeai-c7479',
    authDomain: 'healthbridgeai-c7479.firebaseapp.com',
    storageBucket: 'healthbridgeai-c7479.firebasestorage.app',
  );
}
